#!/usr/bin/python3

""" 
    python script takes the name
    of a state as an argument and list all cities of that state
    using the database

"""

import sys
import MySQLdb

if __name__ == "__main__":

    db = MySQLdb.connect(user=sys.argv[1],
                         passwd=sys.argv[2],
                         db=sys.argv[3],
                         port=3306,
                         host='localhost',
                         )
    cur = db.cursor()
    cur.execute("SELECT cities.name FROM cities WHERE state_id = (SELECT id FROM states WHERE name = '{}'", sys.argv[4])
    #cur.execute(query, (sys.argv[4],))

    rows = cur.fetchall()
    for row in rows:
        print(row)

